### PR TITLE
updated oauth2 to 0.8

### PR DESCRIPTION
**Pull request by kelostrada**
Based on @fajarmf PR to `ueberauth_google`.
Updating oauth2 to `0.8.0`.

### CODE REVIEW

**Comment by doomspork** [comment]
@kelostrada could you please resolve the conflict so this can be merged?  Thank you! 👍

**Comment by kelostrada** [comment]
@doomspork sure, will do tonight ;)

**Comment by kelostrada** [comment]
@doomspork - it's fixed, please check this out!

**Comment by doomspork** [comment]
@kelostrada could you please resolve the merge conflict?  Then I can merge 👍

**Comment by kelostrada** [comment]
@doomspork - fixed again, sorry for the delay

**Comment by doomspork** [comment]
No worries @kelostrada, sorry this has taken so long. 👍

**Pull request merged**
